import type { Chat, Product, Category } from "./types"

export const mockChats: Chat[] = [
  {
    id: "1",
    type: "direct",
    name: "Sarah Johnson",
    avatar: "https://i.pravatar.cc/96?img=1",
    lastMessage: "Hey! Did you check out that new jacket?",
    timestamp: new Date(2026, 1, 16, 14, 32),
    unreadCount: 3,
    hasProduct: false,
  },
  {
    id: "2",
    type: "group",
    name: "Weekend Market Deals",
    avatar: "https://i.pravatar.cc/96?img=10",
    lastMessage: "Check out this deal on sneakers!",
    timestamp: new Date(2026, 1, 16, 13, 15),
    unreadCount: 12,
    hasProduct: true,
  },
  {
    id: "3",
    type: "direct",
    name: "Mike Chen",
    avatar: "https://i.pravatar.cc/96?img=3",
    lastMessage: "I just listed my camera for sale",
    timestamp: new Date(2026, 1, 16, 11, 45),
    unreadCount: 0,
    hasProduct: true,
  },
  {
    id: "4",
    type: "direct",
    name: "Emma Wilson",
    avatar: "https://i.pravatar.cc/96?img=5",
    lastMessage: "Thanks for the quick delivery!",
    timestamp: new Date(2026, 1, 16, 10, 20),
    unreadCount: 0,
    hasProduct: false,
  },
  {
    id: "5",
    type: "group",
    name: "Vintage Collectors",
    avatar: "https://i.pravatar.cc/96?img=12",
    lastMessage: "New vintage watches added",
    timestamp: new Date(2026, 1, 15, 22, 10),
    unreadCount: 5,
    hasProduct: true,
  },
  {
    id: "6",
    type: "direct",
    name: "Alex Rivera",
    avatar: "https://i.pravatar.cc/96?img=7",
    lastMessage: "Is the laptop still available?",
    timestamp: new Date(2026, 1, 15, 18, 30),
    unreadCount: 1,
    hasProduct: false,
  },
  {
    id: "7",
    type: "direct",
    name: "Priya Patel",
    avatar: "https://i.pravatar.cc/96?img=9",
    lastMessage: "Sure, I can ship it tomorrow",
    timestamp: new Date(2026, 1, 15, 15, 0),
    unreadCount: 0,
    hasProduct: false,
  },
  {
    id: "8",
    type: "group",
    name: "Tech Gadgets Hub",
    avatar: "https://i.pravatar.cc/96?img=14",
    lastMessage: "Flash sale starting now!",
    timestamp: new Date(2026, 1, 15, 12, 0),
    unreadCount: 24,
    hasProduct: true,
  },
  {
    id: "9",
    type: "direct",
    name: "Jordan Lee",
    avatar: "https://i.pravatar.cc/96?img=15",
    lastMessage: "Got the package, looks great!",
    timestamp: new Date(2026, 1, 14, 20, 0),
    unreadCount: 0,
    hasProduct: false,
  },
  {
    id: "10",
    type: "direct",
    name: "Rachel Green",
    avatar: "https://i.pravatar.cc/96?img=20",
    lastMessage: "Can you do $50 for the dress?",
    timestamp: new Date(2026, 1, 14, 16, 45),
    unreadCount: 2,
    hasProduct: true,
  },
]

export const mockCategories: Category[] = [
  { id: "all", label: "All", icon: "grid" },
  { id: "electronics", label: "Electronics", icon: "smartphone" },
  { id: "fashion", label: "Fashion", icon: "shirt" },
  { id: "home", label: "Home", icon: "home" },
  { id: "sports", label: "Sports", icon: "dumbbell" },
  { id: "books", label: "Books", icon: "book-open" },
  { id: "automotive", label: "Auto", icon: "car" },
  { id: "toys", label: "Toys", icon: "gamepad-2" },
]

export const mockProducts: Product[] = [
  {
    id: "p1",
    title: "Wireless Noise-Cancelling Headphones",
    price: 89.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    rating: 4.5,
    reviewCount: 234,
    category: "electronics",
    seller: { name: "TechStore", avatar: "https://i.pravatar.cc/48?img=30" },
  },
  {
    id: "p2",
    title: "Vintage Leather Jacket",
    price: 149.00,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 89,
    category: "fashion",
    seller: { name: "VintageVault", avatar: "https://i.pravatar.cc/48?img=31" },
  },
  {
    id: "p3",
    title: "Smart Watch Pro Series",
    price: 199.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
    rating: 4.3,
    reviewCount: 412,
    category: "electronics",
    seller: { name: "GadgetWorld", avatar: "https://i.pravatar.cc/48?img=32" },
  },
  {
    id: "p4",
    title: "Running Shoes Ultra Boost",
    price: 129.00,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 567,
    category: "sports",
    seller: { name: "SportsFit", avatar: "https://i.pravatar.cc/48?img=33" },
  },
  {
    id: "p5",
    title: "Minimalist Desk Lamp",
    price: 45.00,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=400&h=400&fit=crop",
    rating: 4.1,
    reviewCount: 78,
    category: "home",
    seller: { name: "HomeDecor", avatar: "https://i.pravatar.cc/48?img=34" },
  },
  {
    id: "p6",
    title: "Classic Polaroid Camera",
    price: 75.00,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400&h=400&fit=crop",
    rating: 4.6,
    reviewCount: 203,
    category: "electronics",
    seller: { name: "RetroShop", avatar: "https://i.pravatar.cc/48?img=35" },
  },
  {
    id: "p7",
    title: "Organic Cotton T-Shirt",
    price: 35.00,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop",
    rating: 4.4,
    reviewCount: 156,
    category: "fashion",
    seller: { name: "EcoWear", avatar: "https://i.pravatar.cc/48?img=36" },
  },
  {
    id: "p8",
    title: "Ceramic Plant Pot Set",
    price: 28.00,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400&h=400&fit=crop",
    rating: 4.2,
    reviewCount: 95,
    category: "home",
    seller: { name: "GreenThumb", avatar: "https://i.pravatar.cc/48?img=37" },
  },
  {
    id: "p9",
    title: "Bestseller Novel Collection",
    price: 22.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=400&fit=crop",
    rating: 4.9,
    reviewCount: 342,
    category: "books",
    seller: { name: "BookNook", avatar: "https://i.pravatar.cc/48?img=38" },
  },
  {
    id: "p10",
    title: "Yoga Mat Premium",
    price: 55.00,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop",
    rating: 4.5,
    reviewCount: 189,
    category: "sports",
    seller: { name: "ZenFit", avatar: "https://i.pravatar.cc/48?img=39" },
  },
  {
    id: "p11",
    title: "Bluetooth Speaker Portable",
    price: 39.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop",
    rating: 4.3,
    reviewCount: 278,
    category: "electronics",
    seller: { name: "SoundWave", avatar: "https://i.pravatar.cc/48?img=40" },
  },
  {
    id: "p12",
    title: "Handmade Wooden Toy Set",
    price: 42.00,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 64,
    category: "toys",
    seller: { name: "WoodCraft", avatar: "https://i.pravatar.cc/48?img=41" },
  },
]
